services:
  chatmap-ui:
    image: ghcr.io/hotosm/chatmap-ui:latest
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./deploy/frontend/config.json:/usr/share/nginx/html/config.json
    networks:
      - appnet

  chatmap-api:
    image: ghcr.io/hotosm/chatmap-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - chatmap-redis
      - chatmap-db
    environment:
      - REDIS_HOST=chatmap-redis
      - REDIS_PORT=6379
      - SERVER_URL=http://chatmap-go:8001
      - CHATMAP_API_DEBUG=${CHATMAP_API_DEBUG:-false}
      - CHATMAP_API_URL=${CHATMAP_API_URL:-http://localhost:8000}
      - CHATMAP_ENC_KEY=${CHATMAP_ENC_KEY:-0123456789ABCDEF0123456789ABCDEF}
      - CHATMAP_SECRET_KEY=${CHATMAP_SECRET_KEY:-4sup3rs3cret5up3rdummykey}
      - CHATMAP_DB_HOST=${CHATMAP_DB_HOST:-chatmap-db}
      - CHATMAP_DB=${POSTGRES_DB:-chatmap}
      - CHATMAP_DB_USER=${POSTGRES_USER:-admin}
      - CHATMAP_DB_PASSWORD=${POSTGRES_PASSWORD:-0123456789ABCDEF0123456789ABCDEF}
      - CHATMAP_ACCESS_TOKEN_EXPIRE_MINUTES=${CHATMAP_ACCESS_TOKEN_EXPIRE_MINUTES:-120}
      - CHATMAP_EXPIRING_MIN=${CHATMAP_EXPIRING_MIN:-30}
    volumes:
      - ./media:/app/media:rw
      - ./data:/app/data:rw
    networks:
      - appnet

  chatmap-go:
    image: ghcr.io/hotosm/chatmap-im-connector:latest
    environment:
      - REDIS_HOST=chatmap-redis
      - REDIS_PORT=6379
      - CHATMAP_ENC_KEY=${CHATMAP_ENC_KEY:-0123456789ABCDEF0123456789ABCDEF}
    ports:
      - "8001:8001"
    volumes:
      - ./sessions:/app/sessions
    networks:
      - appnet

  chatmap-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - appnet

  chatmap-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

    depends_on:
      - chatmap-ui
      - chatmap-api
    networks:
      - appnet

  chatmap-db:
    image: postgis/postgis:14-3.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chatmap}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-0123456789ABCDEF0123456789ABCDEF}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  chatmap-certbot:
     image: certbot/certbot
     restart: "no"
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
     command: certonly --webroot --webroot-path=/var/www/certbot --email ${CHATMAP_SITE_ADMIN_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${CHATMAP_SITE_DOMAIN}

networks:
  appnet:

volumes:
  data:
  media:
